### ISSUE TITLE
choice "PDF split" crashes program instantly

### ISSUE THREAD

**Issue by Gopherx1** [Swati4star/Images-to-PDF#1153]
Choosing option "PDF split" crashes program instantly.

### Steps to reproduce

I'm trying to split a PDF file with basically never getting an opportunity to load anything. After a second of choosing the option program crashes without comment.

Here is the actual crash report:
```
type: crash
osVersion: google/oriole/oriole:14/UQ1A.231205.015/2023121200:user/release-keys
package: swati4star.createpdf:110
process: swati4star.createpdf
processUptime: 50717 + 35 ms
installer: com.aurora.adroid

java.lang.NoClassDefFoundError: Failed resolution of: Lorg/bouncycastle/crypto/engines/AESFastEngine;
	at com.itextpdf.text.pdf.crypto.AESCipher.<init>(AESCipher.java:62)
	at com.itextpdf.text.pdf.StandardDecryption.update(StandardDecryption.java:84)
	at com.itextpdf.text.pdf.PdfEncryption.decryptByteArray(PdfEncryption.java:792)
	at com.itextpdf.text.pdf.PdfString.decrypt(PdfString.java:221)
	at com.itextpdf.text.pdf.PdfReader.readDecryptedDocObj(PdfReader.java:1081)
	at com.itextpdf.text.pdf.PdfReader.readDocObj(PdfReader.java:1454)
	at com.itextpdf.text.pdf.PdfReader.readPdf(PdfReader.java:732)
	at com.itextpdf.text.pdf.PdfReader.<init>(PdfReader.java:214)
	at com.itextpdf.text.pdf.PdfReader.<init>(PdfReader.java:240)
	at com.itextpdf.text.pdf.PdfReader.<init>(PdfReader.java:254)
	at com.itextpdf.text.pdf.PdfReader.<init>(PdfReader.java:230)
	at swati4star.createpdf.util.PDFUtils.isPDFEncrypted(PDFUtils.java:96)
	at swati4star.createpdf.adapter.MergeFilesAdapter.onBindViewHolder(MergeFilesAdapter.java:50)
	at swati4star.createpdf.adapter.MergeFilesAdapter.onBindViewHolder(MergeFilesAdapter.java:23)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7678)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7761)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6582)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6848)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6688)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6684)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4604)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3981)
	at android.view.View.measure(View.java:27133)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27133)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27133)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:833)
	at android.view.View.measure(View.java:27133)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.cardview.widget.CardView.onMeasure(CardView.java:260)
	at com.google.android.material.card.MaterialCardView.onMeasure(MaterialCardView.java:160)
	at android.view.View.measure(View.java:27133)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27133)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
	at android.view.View.measure(View.java:27133)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
	at android.view.View.measure(View.java:27133)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27133)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27133)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27133)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:750)
	at android.view.View.measure(View.java:27133)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4379)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2944)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3270)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2650)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9526)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
	at android.view.Choreographer.doFrame(Choreographer.java:882)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8216)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.crypto.engines.AESFastEngine
	... 90 more

```

### Expected behaviour

Give me a file chooser.

### Actual behaviour

App crashes in split of a second.

### Would you like to work on the issue?

No, sorry!

**Comment by jimkalis16** [comment]
hi i would like to work on that if thats ok with you

**Comment by Gopherx1** [comment]
Hi, it's ok with me!
----------------------------------------

From: jimkalis ***@***.***>
To: Swati4star/Images-to-PDF ***@***.***>
CC: Gopherx1 ***@***.***>; Author ***@***.***>
Date: Dec 28, 2023 19:03:43
Subject: Re: [Swati4star/Images-to-PDF] choice "PDF split" crashes program instantly (Issue #1153)

**Comment by jimkalis16** [comment]
it seems to work fine on my pc

**Comment by tlang99** [comment]
Did you get this resolved? I'd like to take a look at it if possible

**Comment by jimkalis16** [comment]
i didn't fix it
