### ISSUE TITLE
[Text to PDF] Permissions error

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#367]
### Steps
- Go to app info & turn off the storage permissions
- Open the app. The runtime permission dialog opens up. `Deny` the permissions
- Go to `Text to PDF` section
- Select a text file. Select `Convert to PDF`

### Actual behaviour
Nothing happens (An internal error occurs)
```
java.io.FileNotFoundException: /storage/emulated/0/PDFfiles/bhuy.pdf (Permission denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:287)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:223)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:110)
        at swati4star.createpdf.util.PDFUtils.createPdf(PDFUtils.java:79)
        at swati4star.createpdf.fragment.TextToPdfFragment.createPdf(TextToPdfFragment.java:309)
        at swati4star.createpdf.fragment.TextToPdfFragment.lambda$openCreateTextPdf$5$TextToPdfFragment(TextToPdfFragment.java:281)
        at swati4star.createpdf.fragment.TextToPdfFragment$$Lambda$3.onInput(Unknown Source:24)
        at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:419)
        at android.view.View.performClick(View.java:6256)
        at android.view.View$PerformClick.run(View.java:24701)
08-10 20:35:40.765 4852-4852/swati4star.createpdf W/System.err:     at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
```

### Expected behaviour
On selecting `Create PDF`, show the runtime permissions dialog (similar to `Images to PDF`)
Go on with creating PDF, only after permissions are given to the app.

**Comment by Swati4star** [comment]
@vyankatesh24 The read & write permission should be enough for this. 👍
