### ISSUE TITLE
[Bug] App crashed, when pdf created from snapshot of camera

### ISSUE THREAD

**Issue by sasfmlzr** [Swati4star/Images-to-PDF#438]
Click Images to PDF - SELECT IMAGES - Camera - Snapshot - Create PDF.
After click Create PDF - stacktrace.
`W/4star.createpd: Accessing hidden field Landroid/widget/TextView;->mCursorDrawableRes:I (light greylist, reflection)
    Accessing hidden field Landroid/widget/TextView;->mEditor:Landroid/widget/Editor; (light greylist, reflection)
D/MDTintHelper: Device issue with cursor tinting: No field mCursorDrawable in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes2.dex)
W/System.err: java.lang.NoSuchFieldException: No field mCursorDrawable in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes2.dex)
W/System.err:     at java.lang.Class.getDeclaredField(Native Method)
        at com.afollestad.materialdialogs.internal.MDTintHelper.setCursorTint(MDTintHelper.java:183)
W/System.err:     at com.afollestad.materialdialogs.internal.MDTintHelper.setTint(MDTintHelper.java:171)
        at com.afollestad.materialdialogs.DialogInit.setupInputDialog(DialogInit.java:527)
W/System.err:     at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:346)
W/System.err:     at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:92)
W/System.err:     at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:2183)
W/System.err:     at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:2188)
        at swati4star.createpdf.fragment.ImageToPdfFragment.createPdf(ImageToPdfFragment.java:237)
W/System.err:     at swati4star.createpdf.fragment.ImageToPdfFragment_ViewBinding$1.doClick(ImageToPdfFragment_ViewBinding.java:37)
W/System.err:     at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
W/System.err:     at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
W/System.err:     at android.view.View.access$3100(View.java:778)
W/System.err:     at android.view.View$PerformClick.run(View.java:25885)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
W/System: A resource failed to call close. `

Then enter the name and pressed ok. App crashed.
Stacktrace:
`W/4star.createpd: Verification of com.airbnb.lottie.model.layer.Layer com.airbnb.lottie.parser.LayerParser.parse(android.util.JsonReader, com.airbnb.lottie.LottieComposition) took 119.217ms
V/stage 1: store the pdf in sd card
D/EGL_emulation: eglMakeCurrent: 0xd75c2680: ver 3 0 (tinfo 0xeba03200)
D/EGL_emulation: eglMakeCurrent: 0xd75c2680: ver 3 0 (tinfo 0xeba03200)
D/EGL_emulation: eglMakeCurrent: 0xd75c2680: ver 3 0 (tinfo 0xeba03200)
W/4star.createpd: Verification of com.airbnb.lottie.model.content.ContentModel com.airbnb.lottie.parser.ContentModelParser.parse(android.util.JsonReader, com.airbnb.lottie.LottieComposition) took 416.870ms
V/stage 2: Document Created
V/Stage 3: Pdf writer
V/Stage 4: Document opened
W/System.err: java.io.FileNotFoundException: / exists, but is not accessible
W/System.err:     at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
        at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
        at java.net.URL.openStream(URL.java:1072)
W/System.err:     at com.itextpdf.text.Image.getInstance(Image.java:257)
        at com.itextpdf.text.Image.getInstance(Image.java:238)
        at com.itextpdf.text.Image.getInstance(Image.java:361)
W/System.err:     at swati4star.createpdf.util.CreatePdf.doInBackground(CreatePdf.java:109)
        at swati4star.createpdf.util.CreatePdf.doInBackground(CreatePdf.java:27)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
W/swati4star.createpdf: type=1400 audit(0.0:51): avc: denied { read } for comm=4173796E635461736B202333 name="/" dev="vda1" ino=2 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
W/LOTTIE: Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove().
I/chatty: uid=10088(swati4star.createpdf) AsyncTask #4 identical 3 lines
W/LOTTIE: Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove().
W/LOTTIE: Animation contains merge paths but they are disabled.
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
    Process: swati4star.createpdf, PID: 9994
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: ExceptionConverter: java.io.IOException: The document has no pages.
     Caused by: java.io.IOException: The document has no pages.
        at com.itextpdf.text.pdf.PdfPages.writePageTree(PdfPages.java:112)
        at com.itextpdf.text.pdf.PdfWriter.close(PdfWriter.java:1256)
        at com.itextpdf.text.pdf.PdfDocument.close(PdfDocument.java:900)
        at com.itextpdf.text.Document.close(Document.java:415)
        at swati4star.createpdf.util.CreatePdf.doInBackground(CreatePdf.java:150)
        at swati4star.createpdf.util.CreatePdf.doInBackground(CreatePdf.java:27)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
I/chatty: uid=10088(swati4star.createpdf) 4star.createpdf identical 3 lines
W/LOTTIE: Animation contains merge paths but they are disabled.
I/Process: Sending signal. PID: 9994 SIG: 9
Disconnected from the target VM, address: 'localhost:8603', transport: 'socket'
`

**Comment by sasfmlzr** [comment]
After crached file saved with 0 bytes and it encrypted.
![image](https://user-images.githubusercontent.com/32689674/46206061-80665400-c32b-11e8-9dd8-3ee752f40950.png)

**Comment by Swati4star** [comment]
Good finding!

**Comment by anirudh8860** [comment]
it's actually working on my device

**Comment by Swati4star** [comment]
I have fixed the crash.
In my device, if I click the image from this camera, the image is empty.

**Comment by anirudh8860** [comment]
Ok cool
