### ISSUE TITLE
App Crashing when clicked on History on HomeActivity

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#585]
### Description
  App Crashes when clicked on History, Add Password, Remove Password, Add Images and some others on HomeActivity.
Error: IndexOutofBoundException 

Also appropriate menu is not getting highlighted in Navigation Drawer.
### Steps to reproduce
* Open App. 
* And click on any of the above option
### Actual behaviour 
App Crashes

### Expected behaviour
Should open respective fragment.

**Comment by srv-twry** [comment]
@vyankatesh24 Could you please paste the whole stacktrace instead of just the Error?

**Comment by vyankatesh24** [comment]
> @vyankatesh24 Could you please paste the whole stacktrace instead of just the Error?

java.lang.IndexOutOfBoundsException: Index: 11, Size: 7
        at java.util.ArrayList.get(ArrayList.java:411)
        at android.support.v7.view.menu.MenuBuilder.getItem(MenuBuilder.java:758)
        at swati4star.createpdf.activity.MainActivity.setNavigationViewSelection(MainActivity.java:398)
        at swati4star.createpdf.fragment.HomeFragment.setNavigationViewSelection(HomeFragment.java:138)
        at swati4star.createpdf.fragment.HomeFragment.highLightNavigationDrawerItem(HomeFragment.java:240)
        at swati4star.createpdf.fragment.HomeFragment.onClick(HomeFragment.java:147)
        at android.view.View.performClick(View.java:5647)
        at android.view.View$PerformClick.run(View.java:22465)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6238)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
