### ISSUE TITLE
The app crashed when I tried to convert a password protected PDF file to Image

### ISSUE THREAD

**Issue by sagorahmed** [Swati4star/Images-to-PDF#727]
#### Expected behavior
The users should be able to convert a password protected PDF file to Image without crashing the app.

#### Actual behavior
When I tried to convert a password protected PDF file to Image, sometimes it crashed immediately/ after a few attempts.

#### How to reproduce
1. Open the app.
2. Then go to "PDF to Images".
3. Swipe up the view files menu.
4. Choose and click on a password protected PDF file. (If you don't have any password protected file then download from somewhere or create a new one from "Add password" menu).
5. Then click on "CREATE IMAGES" and notice the crash. (Sometimes it crashes after a few attempts.)

* App version: 8.6.5
* Operating system: Android 6.0.1

#### Recording Of The Bug
![imagetopdf](https://media.giphy.com/media/XfKACzxiOhmm8Y0iSz/giphy.gif)

#### LogCat
```
04-22 12:15:35.743 22730 22788 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #4

04-22 12:15:35.743 22730 22788 E AndroidRuntime: Process: swati4star.createpdf, PID: 22730

04-22 12:15:35.743 22730 22788 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()

04-22 12:15:35.743 22730 22788 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)

04-22 12:15:35.743 22730 22788 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)

04-22 12:15:35.743 22730 22788 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)

04-22 12:15:35.743 22730 22788 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)

04-22 12:15:35.743 22730 22788 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)

04-22 12:15:35.743 22730 22788 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)

04-22 12:15:35.743 22730 22788 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)

04-22 12:15:35.743 22730 22788 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)

04-22 12:15:35.743 22730 22788 E AndroidRuntime: Caused by: java.lang.IllegalStateException: cannot load page

04-22 12:15:35.743 22730 22788 E AndroidRuntime: 	at android.graphics.pdf.PdfRenderer.nativeOpenPageAndGetSize(Native Method)

04-22 12:15:35.743 22730 22788 E AndroidRuntime: 	at android.graphics.pdf.PdfRenderer.access$300(PdfRenderer.java:101)

04-22 12:15:35.743 22730 22788 E AndroidRuntime: 	at android.graphics.pdf.PdfRenderer$Page.<init>(PdfRenderer.java:276)

04-22 12:15:35.743 22730 22788 E AndroidRuntime: 	at android.graphics.pdf.PdfRenderer$Page.<init>(PdfRenderer.java:254)

04-22 12:15:35.743 22730 22788 E AndroidRuntime: 	at android.graphics.pdf.PdfRenderer.openPage(PdfRenderer.java:203)

04-22 12:15:35.743 22730 22788 E AndroidRuntime: 	at swati4star.createpdf.util.PdfToImages.doInBackground(PdfToImages.java:62)

04-22 12:15:35.743 22730 22788 E AndroidRuntime: 	at swati4star.createpdf.util.PdfToImages.doInBackground(PdfToImages.java:22)

04-22 12:15:35.743 22730 22788 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)

04-22 12:15:35.743 22730 22788 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)

04-22 12:15:35.743 22730 22788 E AndroidRuntime: 	... 4 more
```

**Comment by Swati4star** [comment]
Thank you for reporting @sagorahmed !

**Comment by sagorahmed** [comment]
Thanks, @Swati4star

**Comment by jddeep** [comment]
@Swati4star @vyankatesh24 I will work on this.

**Comment by jddeep** [comment]
@Swati4star @vyankatesh24 Please have a look here. I was trying to reproduce this on my device by creating password protected pdfs and then trying to convert from PDF to Images. But all works fine for me,

**Comment by vyankatesh24** [comment]
@jddeep 
This error comes while conversion of password protected PDF and snackbar shows "We could find any image..."

``` 
java.lang.SecurityException: cannot create document. Error: 4
        at android.graphics.pdf.PdfRenderer.nativeCreate(Native Method)
        at android.graphics.pdf.PdfRenderer.<init>(PdfRenderer.java:165)
        at swati4star.createpdf.util.PdfToImages.doInBackground(PdfToImages.java:59)
        at swati4star.createpdf.util.PdfToImages.doInBackground(PdfToImages.java:22)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
```
