### ISSUE TITLE
App crashes on 'Add Text' click on Home Fragment

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#771]
`Add Text` works when clicked on Navigation drawer item. App crashes on `Add Text` click on Home Fragment.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: swati4star.createpdf, PID: 29334
    java.lang.NullPointerException: Attempt to invoke virtual method 'int swati4star.createpdf.model.HomePageItem.getNavigationItemId()' on a null object reference
        at swati4star.createpdf.fragment.HomeFragment.onClick(HomeFragment.java:133)
        at android.view.View.performClick(View.java:5647)
        at android.view.View$PerformClick.run(View.java:22465)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6238)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
```

**Comment by rob729** [comment]
@vyankatesh24 I would like to work on this issue.
